name: phone_input_field
description: A Flutter package for international phone number input with country selection. Features a country picker dialog with search and customizable phone input field.
version: 0.0.1
publish_to: "https://pub.dev"

homepage: https://github.com/kabirdeula/phone_input_field
repository: https://github.com/kabirdeula/phone_input_field
issue_tracker: https://github.com/kabirdeula/phone_input_field/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - phone-input
  - country-selector
  - internalization
  - ui-widgets